cloud:
  aws:
    credentials:
      access-key: AKIARPQYIW7LV6FO6SWH
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: partyplanning


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9090