cloud:
  aws:
    credentials:
      access-key: AKIARPQYIW7LYVFIQQHB
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: partyplanning


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9090